# https://pnpm.io/pnpm-workspace_yaml
packages:
  # all packages in direct subdirs of packages/
  - 'projects/*'
  - 'demos/*'
  - 'packages/*'
  # all packages in subdirs of components/
  # - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
